name: todo_hive
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  socket_io_client: ^2.0.2
  google_sign_in: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  go_router: 6.0.2
  dio: ^5.1.1

  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
